import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const LANGS = ['en', 'de']

const T = {
  en: {
    // Navbar
    logIn: 'Log In',
    signUp: 'Sign Up',
    signOut: 'Sign out',
    profile: 'Profile',
    deliveredTo: 'Delivered to',
    selectAddress: 'Select Address',
    savedAddresses: 'Saved Addresses',
    addNewAddress: 'Add New Address',

    // Landing page
    heroTagline: 'Halal Certified Suppliers Only',
    heroTitle: 'The Smarter Way to Stock Your Halal Kitchen',
    heroSubtitle: 'Connect with verified Halal suppliers and order everything your restaurant needs track, manage, and optimize, all from ProCuro.',
    getStarted: 'Get Started Free',
    browseSuppliers: 'Browse Suppliers',
    trustedBy: 'Trusted by Halal restaurants across Germany',
    featuredSuppliers: 'Featured Suppliers',
    viewAll: 'View All',
    viewAllSuppliers: 'View All Suppliers',
    featuredProducts: 'Featured Products',
    whyProcuro: 'Why ProCuro?',
    whySubtitle: 'Everything you need to run a modern Halal kitchen',
    verifiedHalal: 'Verified Halal Suppliers',
    verifiedHalalDesc: 'Every supplier is manually reviewed and Halal-certified before joining the platform.',
    oneClickOrdering: 'One-Click Ordering',
    oneClickDesc: 'Browse, compare, and order from multiple suppliers in a single cart.',
    realTimeTracking: 'Real-Time Tracking',
    realTimeDesc: 'Track every order from confirmation to delivery — no more chasing suppliers.',
    ctaTitle: 'Ready to simplify your Halal supply chain?',
    ctaSubtitle: 'Join hundreds of restaurants already saving time and money with ProCuro.',
    startFree: 'Start for Free',
    learnMore: 'Learn More',

    // Profile pages
    profilePicture: 'Profile Picture',
    editProfile: 'Edit Profile',
    businessDetails: 'Business Details',
    accountSettings: 'Account Settings',
    languageSprache: 'Language / Sprache',
    changeEmailPassword: 'Change Email & Password',
    updatePhoneNumber: 'Update Phone Number',
    manageMyAddresses: 'Manage My Addresses',
    deleteAccount: 'Delete Account',
    viewMyOrders: 'View My Orders',
    viewAnalysis: 'View Analysis',
    mySales: 'My Sales',
    restaurant: 'Restaurant',
    supplier: 'Supplier',
    restaurantOwner: 'Restaurant Owner',
    taxIdVat: 'Tax ID / VAT',
    city: 'City',
    cuisineType: 'Cuisine / Type',
    categories: 'Categories',
    businessLocations: 'Business Locations',
    bankDetails: 'Bank Details',
    add: 'Add',
    addAddress: 'Add address',
    addTaxId: 'Add Tax ID',
    addBankDetails: 'Add bank details',
    notSet: 'Not set',
    saveChanges: 'Save Changes',
    selected: 'selected',
    locationsHelp: 'Tap each location you want shown on your profile',
    manageAddresses: 'Manage Addresses',
    cityLocation: 'City / Location',
    useGps: 'Use GPS',
    useMyLocation: 'Use My Location',
    detecting: 'Detecting…',
    halal: 'Halal',
    aboutOptional: 'A short description about your restaurant...',
    yourName: 'Your Name',
    restaurantName: 'Restaurant Name',
    businessName: 'Business Name',
    description: 'Description',
    bio: 'About',
    website: 'Website (optional)',
    requiredField: '* Required',

    // AI
    aiInsights: 'AI Insights',
    poweredByGemini: 'Powered by Gemini',
    refreshInsights: 'Refresh insights',
    tryAgain: 'Try again',
    generateInsights: 'Generate Insights',
    analyseYourSales: 'Analyse your sales data',
    aiHelpText: 'Get AI-powered insights on revenue, top products, and growth opportunities.',

    // Common
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    back: 'Back',
    loading: 'Loading…',
    submit: 'Submit',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    filter: 'Filter',
    addToCart: 'Add to Cart',
    order: 'Order',
    orders: 'Orders',
    products: 'Products',
    analytics: 'Analytics',
    settings: 'Settings',
    language: 'Language',
    halalCertified: 'Halal Certified',
    rating: 'Rating',
    location: 'Location',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',

    // Landing page extra
    browseByCategory: 'Browse by Category',
    howItWorks: 'How It Works',
    howItWorksStep1Title: 'Create Your Account',
    howItWorksStep1Desc: 'Sign up as a restaurant owner or supplier in minutes. No hidden fees.',
    howItWorksStep2Title: 'Browse & Order',
    howItWorksStep2Desc: 'Browse verified Halal suppliers and place orders with a single click.',
    howItWorksStep3Title: 'Track Delivery',
    howItWorksStep3Desc: 'Track your delivery in real-time and manage all orders from one place.',
    gdprCompliant: 'GDPR Compliant',
    halalVerifiedBadge: 'Halal Verified Suppliers',
    noHiddenFees: 'No Hidden Fees',
    noProductsFound: 'No products found. Be the first supplier to list products!',
    noSuppliersYet: 'No verified suppliers yet.',
    outOfStock: 'Out of Stock',
    statsRestaurants: 'Restaurants',
    statsVerifiedSuppliers: 'Verified Suppliers',
    statsOrdersPlaced: 'Orders Placed',
    statsAverageRating: 'Average Rating',
    catAll: 'All',
    catMeat: 'Meat',
    catPoultry: 'Poultry',
    catSeafood: 'Seafood',
    catDairy: 'Dairy',
    catVegetables: 'Vegetables',
    catFruits: 'Fruits',
    catBakery: 'Bakery',
    catBeverages: 'Beverages',
    catSpices: 'Spices',
    catOther: 'Other',

    // About page
    aboutTitle: 'About ProCuro',
    aboutIntro: 'ProCuro is a B2B Halal procurement platform connecting verified Halal suppliers with restaurant owners across Germany. Our mission is to make Halal supply chains transparent, efficient, and trustworthy.',
    aboutCard1Title: 'Verified Halal',
    aboutCard1Desc: 'Every supplier on ProCuro holds a valid Halal certification reviewed by our admin team.',
    aboutCard2Title: 'Community First',
    aboutCard2Desc: 'Built for the Halal business community in Germany — suppliers, restaurant owners, and caterers.',
    aboutCard3Title: 'Made in Germany',
    aboutCard3Desc: 'Headquartered in Paderborn, NRW. Fully compliant with German and EU regulations.',
    aboutOurStory: 'Our Story',
    aboutStoryP1: 'ProCuro was founded to solve a real problem: restaurant owners in Germany struggled to find reliable, certified Halal suppliers — and suppliers had no easy way to reach their customers. We built a platform that bridges this gap with a seamless ordering system, real-time communication, and transparent certification verification.',
    aboutStoryP2: 'Today, ProCuro serves dozens of verified suppliers and hundreds of restaurants across Germany, with a focus on quality, trust, and community.',
    contactUs: 'Contact Us',
    aboutLocation: 'Location: Paderborn, North Rhine-Westphalia, Germany',

    // Careers page
    careersTitle: 'Careers at ProCuro',
    careersSubtitle: 'Join us in building the future of Halal procurement in Germany.',
    careersWhyTitle: 'Why ProCuro?',
    careersWhyDesc: "We're a mission-driven startup based in Paderborn, NRW, solving a real problem for the Halal business community. We offer a collaborative environment, competitive salaries, flexible working arrangements, and the chance to make a meaningful impact.",
    careersOpenPositions: 'Open Positions',
    careersApplyEmail: 'Apply via Email',
    careersNoRole: "Don't see your role? We'd still love to hear from you.",
    careersSpontaneous: 'Send a spontaneous application →',
    careersJob1Title: 'Full-Stack Developer (React / Node.js)',
    careersJob1Type: 'Full-Time',
    careersJob1Location: 'Paderborn, NRW (Remote-friendly)',
    careersJob1Desc: 'Help build and scale our procurement platform. Experience with React, Supabase, and TypeScript preferred.',
    careersJob2Title: 'Business Development Manager',
    careersJob2Type: 'Full-Time',
    careersJob2Location: 'Paderborn, NRW',
    careersJob2Desc: 'Drive partnerships with Halal suppliers and restaurant chains across Germany. German and English required.',
    careersJob3Title: 'Customer Success Specialist',
    careersJob3Type: 'Part-Time / Full-Time',
    careersJob3Location: 'Remote (Germany)',
    careersJob3Desc: 'Support our growing supplier and restaurant owner community. Fluent German required.',

    // Press page
    pressTitle: 'Press & Media',
    pressSubtitle: 'Information and resources for journalists and media professionals.',
    pressAboutTitle: 'About ProCuro',
    pressAboutDesc: "ProCuro is Germany's leading B2B Halal procurement platform, connecting verified Halal suppliers with restaurant owners and caterers. Founded in Paderborn, NRW, ProCuro brings transparency, trust, and efficiency to Halal supply chains across Germany.",
    pressKeyFacts: 'Key Facts',
    pressFoundedLabel: 'Founded',
    pressHQLabel: 'HQ',
    pressMarketLabel: 'Market',
    pressPlatformLabel: 'Platform',
    pressLanguagesLabel: 'Languages',
    pressMarketValue: 'B2B Halal food procurement, Germany',
    pressPlatformValue: 'Web-based SaaS (React / Supabase)',
    pressLanguagesValue: 'German, English, Arabic (planned)',
    pressContactTitle: 'Press Contact',
    pressContactDesc: 'For press inquiries, interview requests, or media assets, please reach out to our team.',
    pressContactButton: 'Contact Press Team',
    pressBrandAssetsTitle: 'Brand Assets',
    pressBrandAssetsDesc: 'Logo files, brand guidelines, and high-res images available on request. Email us at support@procuro.com.',
    pressStatRestaurants: 'Restaurants',
    pressStatSuppliers: 'Suppliers',
    pressStatRating: 'Platform Rating',

    // Help Center page
    helpTitle: 'Help Center',
    helpSubtitle: "Have a question or issue? Fill out the form below and we'll get back to you within 24 hours.",
    helpNameLabel: 'Name *',
    helpNamePlaceholder: 'Your name',
    helpEmailPlaceholder: 'you@example.com',
    helpTopicLabel: 'Topic',
    helpTopicPlaceholder: 'Select a topic...',
    helpMessageLabel: 'Message *',
    helpMessagePlaceholder: 'Describe your issue in detail...',
    helpSendMessage: 'Send Message',
    helpEmailDirect: 'Or email us directly at',
    helpSentTitle: 'Message sent!',
    helpSentDesc: 'Your email client should have opened. If not, email us directly at',
    helpRequiredError: 'Please fill in all required fields',
    helpTopicAccount: 'Account & Registration',
    helpTopicOrders: 'Orders & Delivery',
    helpTopicPayments: 'Payments & Invoicing',
    helpTopicHalal: 'Halal Certification',
    helpTopicTechnical: 'Technical Issue',
    helpTopicOther: 'Other',

    // Legal pages
    privacyTitle: 'Privacy Policy',
    privacySubtitle: 'Last updated: May 2025',
    privacyLegalNote: 'This privacy policy (Datenschutzerklärung) is provided in German as required by GDPR/DSGVO. For an English summary, contact us at support@procuro.com.',
    termsTitle: 'Terms of Service',
    termsSubtitle: 'Effective: May 2025',
    termsLegalNote: 'Our Terms of Service (Allgemeine Geschäftsbedingungen) are in German as required by German law. For an English summary, contact us at support@procuro.com.',

    // Sidebar navigation
    navStore: 'Store',
    navCart: 'Cart',
    navOrders: 'Orders',
    navAnalytics: 'Analytics',
    navMessages: 'Messages',
    navProfile: 'Profile',
    navDashboard: 'Dashboard',
    navProducts: 'Products',

    // Notifications
    notifications: 'Notifications',
    markAllRead: 'Mark all read',
    noNotificationsYet: 'No notifications yet',

    // Footer
    footerCompany: 'Company',
    footerResources: 'Resources',
    footerContact: 'Contact',
    footerAboutUs: 'About Us',
    footerCareers: 'Careers',
    footerPress: 'Press',
    footerHelpCenter: 'Help Center',
    footerPrivacyPolicy: 'Privacy Policy',
    footerTermsOfService: 'Terms of Service',
    footerCopyright: '© 2026 ProCuro GmbH. All rights reserved.',
    footerTagline: 'Empowering Halal businesses with seamless procurement and inventory solutions across Germany.',

    // Store / Products
    categoriesLabel: 'Categories',
    recommendedSuppliers: 'Recommended Suppliers',
    recommendedOrders: 'Recommended Orders',
    seeAll: 'See All',
    allProductsTitle: 'All Products',
    allSuppliersTitle: 'All Suppliers',
    nearMe: 'Near Me',
    sortLabel: 'Sort',
    filterLabel: 'Filter',
    sortRecommended: 'Recommended',
    sortPriceAsc: 'Price: Low to High',
    sortPriceDesc: 'Price: High to Low',
    sortNameAZ: 'Name A–Z',
    sortTopRated: 'Top Rated',
    searchProductsPlaceholder: 'Search Halal products...',
    searchSuppliersPlaceholder: 'Search suppliers by name or city...',
    outOfStockText: 'Out of Stock',
    clearFilters: 'Clear filters',
    noProductsFoundSearch: 'No products found',
    noSuppliersFound: 'No suppliers found',
    pendingReview: 'Pending Review',
    halalCertifiedBadge: 'Halal Certified',
    completeProfileBtn: 'Complete Profile',
    completeProfileWarning: 'Complete your profile to place orders',
    missingLabel: 'Missing',
    allowLocation: 'Allow',
    allowLocationTitle: 'Allow location for accurate delivery fees',
    locationDesc: 'We use your location to calculate the delivery fee from each supplier.',
    locationBlocked: 'Location blocked in browser settings',
    locationBlockedDesc: 'Enable location for this site in your browser settings, or enter your address manually in your profile.',
    addManually: 'Add Manually',
    noSuppliersYetStore: 'No suppliers yet.',

    // Orders
    placedOrders: 'Placed Orders',
    ordersOngoing: 'Ongoing',
    ordersCompleted: 'Completed',
    noOrdersYet: 'No orders yet.',
    unitPrice: 'Unit Price',
    qtyOrdered: 'Qty Ordered',
    subtotalText: 'Subtotal',
    downloadInvoice: 'Download Invoice',
    cancelOrder: 'Cancel Order',
    confirmDelivery: 'Confirm Delivery',
    orderFrom: 'Order from',
    viewDetails: 'View Details',
    backToOrders: 'Back to Orders',
    cancellationReason: 'Cancellation Reason',
    refundReceipt: 'Refund Receipt',
    disputeDelivery: 'Dispute Delivery',
    rateOrder: 'Rate Order',
    orderItems: 'Order Items',
    paymentMethod: 'Payment Method',
    deliveryFee: 'Delivery Fee',
    totalAmount: 'Total Amount',
    orderNote: 'Note',

    // Cart
    cartTitle: 'Your Cart',
    cartEmpty: 'Your cart is empty',
    cartEmptyDesc: 'Start browsing our verified Halal suppliers',
    browseStore: 'Browse Store',
    reviewOrder: 'Review Order',
    paymentLabel: 'Payment Method',
    orderPlaced: 'Order Placed!',
    bankTransfer: 'Bank Transfer',
    cashOnDelivery: 'Cash on Delivery',
    deliveryAddress: 'Delivery Address',
    placeOrderBtn: 'Place Order',
    continueShopping: 'Continue Shopping',
    cartStep1: 'Cart',
    cartStep2: 'Payment',
    cartStep3: 'Done',

    // Supplier profile (public)
    supplierProducts: 'Products',
    supplierAbout: 'About',
    supplierCertifications: 'Certifications',
    supplierLocations: 'Locations',
    orderFromSupplier: 'Order from this Supplier',
    messageSupplier: 'Message Supplier',
    reportSupplier: 'Report Supplier',
    noProductsListed: 'No products listed yet',
    noCertificatesAvailable: 'No certificates available',
    noDescriptionProvided: 'No description provided',
    showLess: 'Show Less',
    seeAllProducts: 'See All',
    verified: 'Verified',
    shareProfile: 'Share',

    // Account deleted page
    accountDeletedTitle: 'Goodbye & Thank You',
    accountDeletedSubtitle: 'Your account has been deleted',
    accountDeletedMessage: "We're truly sorry to see you go. It has been an honour being part of your journey, and we hope ProCuro made your work a little easier along the way. We wish you all the success and happiness in everything ahead — you will always be welcome back. 🌙",
    accountDeletedThanks: 'Thank you for being part of the ProCuro family. We are grateful for the trust you placed in us. ✨💙',
    accountDeletedCta: 'Back to Homepage',

    // Login / auth
    loginTagline: 'The Halal Procurement Platform',
    emailAddressLabel: 'Email Address',
    passwordLabel: 'Password',
    forgotPassword: 'Forgot password?',
    loggingIn: 'Logging in...',
    orContinueWith: 'OR CONTINUE WITH',
    dontHaveAccount: "Don't have an account?",
    forgotPasswordTitle: 'Forgot your password?',
    forgotPasswordDesc: "Enter your email and we'll send you a reset link.",
    backToLoginBtn: '← Back to login',
    sendResetLink: 'Send Reset Link',
    sending: 'Sending...',
    checkYourEmail: 'Check your email',
    resetLinkSentTo: 'We sent a password reset link to:',
    resetLinkExpiry: 'Click the link in the email to set a new password. The link expires in 1 hour.',

    // Register
    createFreeAccount: 'Create your free account',
    fullNameLabel: 'Full Name',
    passwordStrengthLabel: 'Strength',
    pwStrengthWeak: 'Weak',
    pwStrengthGood: 'Good',
    pwStrengthStrong: 'Strong',
    pwReqLength: 'Over 8 characters',
    pwReqUppercase: 'One uppercase letter',
    pwReqSpecial: 'Special character (@#$%...)',
    confirmPasswordLabel: 'Confirm Password',
    createAccountBtn: 'Create Account',
    creatingAccount: 'Creating Account...',
    passwordsNoMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    alreadyHaveAccount: 'Already have an account?',

    // Select role
    welcomeToProcuro: 'Welcome to ProCuro!',
    accountReadyDesc: "Your account is ready. Now choose how you'll use ProCuro.",
    choiceIsPermanent: 'This choice is permanent and cannot be changed.',
    roleOwnerDesc: 'Browse and order from verified Halal suppliers',
    roleSupplierDesc: 'Sell your Halal products to restaurants across Germany',
    settingUpAccount: 'Setting up your account...',

    // Navbar address form
    newAddress: 'New Address',
    labelFieldPlaceholder: 'Label (e.g. Restaurant)',
    streetFieldPlaceholder: 'Street *',
    postalFieldPlaceholder: 'Postal',
    cityFieldPlaceholder: 'City *',

    // AddToCartModal
    calculatingDeliveryFee: 'Calculating delivery fee…',
    addAddressForDelivery: 'Add an address to see delivery fee',
    deliveryFeeUnavailable: 'Delivery fee unavailable',
    freeDelivery: 'Free delivery',
    deliveryLabelText: 'Delivery:',
    quantity: 'Quantity',
    discountCode: 'Discount Code',
    apply: 'Apply',
    currentlyOutOfStock: 'Currently Out of Stock',
    unavailable: 'Unavailable',
    reportThisProduct: 'Report this product',
    discountApplied: '10% Discount Applied!',
    discountInvalid: 'Code is not correct',
    perUnit: 'per',

    // Orders (owner)
    myOrders: 'My Orders',
    ongoingOrdersTab: 'Ongoing Orders',
    completedOrdersTab: 'Completed Orders',
    orderDetailsTitle: 'Order Details',
    orderIdLabel: 'Order ID',
    dateLabel: 'Date',
    supplierNameLabel: 'Supplier',
    itemsOrderedLabel: 'Items Ordered',
    totalLabel: 'Total',
    cancellationPendingTitle: 'Cancellation Pending',
    cancellationPendingDesc: 'Your cancellation request has been sent to the supplier. They will review and process the refund.',
    orderCancelledTitle: 'Order Cancelled',
    cancelledBySupplierText: 'by Supplier',
    cancelledByYouText: 'by You',
    refundReceiptUploadedTitle: 'Refund Receipt Uploaded',
    refundReceiptUploadedDesc: 'The supplier has uploaded proof of refund. Please verify and confirm below.',
    confirmRefundReceivedBtn: 'Confirm Refund Received',
    viewRefundReceiptLink: 'View Refund Receipt',
    disputePendingTitle: 'Dispute Pending',
    disputePendingDesc: 'Your report has been sent to the supplier. They will respond shortly.',
    disputeResolutionTitle: 'Dispute Resolution',
    suppliersResponseLabel: "Supplier's response:",
    markAsDeliveredBtn: 'Mark as Delivered',
    didntReceiveItBtn: "I Didn't Receive It",
    chatWithSupplierBtn: 'Chat with Supplier',
    reportThisOrder: 'Report this Order',
    markDeliveredBtn: 'Mark Delivered',
    confirmRefundBtn: 'Confirm Refund',
    requestCancellationBtn: 'Request Cancellation',
    keepOrderBtn: 'Keep Order',
    reportNonDeliveryTitle: 'Report Non-Delivery',
    reportNonDeliveryDesc: 'The supplier will be notified and asked to respond. Please tell them what happened — for example: "The driver never arrived" or "Only half of the items were delivered."',
    reasonRequiredLabel: 'Reason *',
    whatHappenedPlaceholder: 'What happened?',
    sendReport: 'Send Report',
    cancelOrderTitle: 'Cancel Order',
    reasonForCancellationLabel: 'Reason for cancellation *',
    cancelReasonPlaceholder: 'e.g. Changed my mind, ordered by mistake, found another supplier...',
    bankTransferCancelNote: 'Your cancellation will be sent to the supplier for review. Once they agree, they will upload proof of the returned payment.',
    bankTransferOrderLabel: 'Bank transfer order',
    disputePendingAwaitSupplier: 'Dispute pending — awaiting supplier response',
    ratingOrderDelivered: 'Order Delivered!',
    ratingHowWouldYouRate: 'How would you rate',
    ratingPoor: 'Poor',
    ratingFair: 'Fair',
    ratingGoodLabel: 'Good',
    ratingVeryGood: 'Very Good',
    ratingExcellent: 'Excellent',
    skipBtn: 'Skip',
    submitRating: 'Submit Rating',
    noTabOrders: 'No orders',
    cancelledPendingLabel: 'Cancellation pending:',
    cancelledBySupplierLabel: 'Cancelled by supplier:',
    cancelledByYouLabel: 'Cancelled by you:',
    disputeResolvedLabel: 'Dispute resolved:',

    // Supplier Orders
    uploadRefundProof: 'Upload refund proof (image or PDF)',
    selectRefundReceipt: 'Select Refund Receipt',
    uploadAndNotifyOwner: 'Upload & Notify Owner',
    bankTransferRefundRequired: 'Bank Transfer Refund Required',
    viewPaymentReceipt: 'View Payment Receipt',
    respondToDisputeTitle: 'Respond to Delivery Dispute',
    ownersMessageLabel: "Owner's message:",
    chooseResolution: 'Choose Resolution',
    resendOrder: 'Re-send Order',
    respondToDisputeBtn: 'Respond to Dispute',
    chatWithOwnerBtn: 'Chat with Owner',
    datePlacedLabel: 'Date Placed',
    statusLabel: 'Status',
    cancellationRequestedByOwner: 'Cancellation Requested by Owner',
    ownerWantsCancelNote: 'The restaurant owner wants to cancel this order.',
    paidViaBankTransferCancelNote: 'Paid via bank transfer — upload the refund proof below to accept this cancellation.',
    cancelledByLabel: 'Cancelled by:',
    waitingForOwnerReceipt: 'Waiting for restaurant owner to upload payment receipt',
    outForDeliveryBtn: 'Mark Out for Delivery',
    confirmOrderBtn: 'Confirm Order',
    refundReceiptUploadedMsg: 'Refund receipt uploaded',
    waitingOwnerConfirmRefund: 'Waiting for the restaurant owner to confirm.',
    noDeliveryAddress: 'No delivery address on file',
    ownerReportedDeliveryDispute: 'Owner reported delivery not received',
    deliveryNotReceived: 'Delivery Not Received',
    ownerReportedNonDelivery: 'The restaurant owner reported they did not receive this order. You must respond.',
    ownersReasonLabel: "Owner's Reason",
    deliveryToLabel: 'Delivery To',
    acceptBtn: 'Accept',
    rejectBtn: 'Reject',
    addProductBtn: 'Add Product',
    editProductBtn: 'Edit Product',
    addNewProductBtn: 'Add New Product',
    noProductsYetSupplier: 'No products yet',
    addFirstProduct: 'Add your first product',
    deliveryFeeStructure: 'Delivery Fee Structure',
    distanceLabel: 'Distance',
    productLabel: 'Product',
    categoryLabel: 'Category',
    priceLabel: 'Price',

    // Analytics charts
    spendPeriod: 'Spend (period)',
    ordersPeriodLabel: 'Orders (period)',
    topCategoryLabel: 'Top Category',
    topProductLabel: 'Top Product',
    spendingTrend: 'Spending Trend',
    topProductsOrdered: 'Top Products Ordered',
    spendingByCategory: 'Spending by Category',
    topCategoriesEur: 'Top Categories (€)',
    noDataForPeriod: 'No data for this period',
    revenueTrend: 'Revenue Trend',
    revenueByProduct: 'Revenue by Product',
    salesByProductPct: 'Sales by Product (%)',
    topRestaurantClients: 'Top Restaurant Clients',
    revenueStatLabel: 'Revenue',
    ordersStatLabel: 'Orders',
    bestProductStatLabel: 'Best Product',
    activeProductsStatLabel: 'Active Products',

    // Account banned
    accountBannedBanner: 'Your account has been banned. Contact support to appeal.',
    accountBannedTitle: 'Account Banned',
    accountBannedContent: 'Your account has been suspended by an administrator. Only the chat feature is available to contact support.',

    // Supplier banned (visible to restaurant owners)
    supplierBannedTitle: 'This supplier account is banned',
    supplierBannedBanner: 'This supplier has been banned by an administrator for violating our terms. You cannot place new orders, but you can still view their profile and any previous orders.',
    supplierBannedShort: 'Banned',
    supplierBannedChatNotice: 'This supplier\'s account has been banned. Past orders remain accessible but new orders cannot be placed.',
    supplierBannedCartNotice: 'This supplier has been banned. Please remove their items to continue checkout.',
    supplierBannedCannotAdd: 'Cannot add — supplier is banned',

    // Owner banned (visible to suppliers)
    ownerBannedTitle: 'This restaurant account is banned',
    ownerBannedBanner: 'This restaurant owner has been banned by an administrator for violating our terms. Their previous orders remain visible, but they can no longer place new orders.',
    ownerBannedShort: 'Banned',
    ownerBannedChatNotice: 'This restaurant owner\'s account has been banned. Past orders remain accessible but no new orders can be placed.',
  },
  de: {
    // Navbar
    logIn: 'Anmelden',
    signUp: 'Registrieren',
    signOut: 'Abmelden',
    profile: 'Profil',
    deliveredTo: 'Lieferung an',
    selectAddress: 'Adresse wählen',
    savedAddresses: 'Gespeicherte Adressen',
    addNewAddress: 'Neue Adresse hinzufügen',

    // Landing page
    heroTagline: 'Nur Halal-zertifizierte Lieferanten',
    heroTitle: 'Der clevere Weg, Ihre Halal-Küche zu versorgen',
    heroSubtitle: 'Verbinden Sie sich mit geprüften Halal-Lieferanten und bestellen Sie alles, was Ihr Restaurant braucht verfolgen, verwalten und optimieren, alles mit ProCuro.',
    getStarted: 'Kostenlos starten',
    browseSuppliers: 'Lieferanten entdecken',
    trustedBy: 'Vertraut von Halal-Restaurants in ganz Deutschland',
    featuredSuppliers: 'Empfohlene Lieferanten',
    viewAll: 'Alle anzeigen',
    viewAllSuppliers: 'Alle Lieferanten anzeigen',
    featuredProducts: 'Empfohlene Produkte',
    whyProcuro: 'Warum ProCuro?',
    whySubtitle: 'Alles, was Sie für eine moderne Halal-Küche brauchen',
    verifiedHalal: 'Geprüfte Halal-Lieferanten',
    verifiedHalalDesc: 'Jeder Lieferant wird manuell geprüft und Halal-zertifiziert, bevor er der Plattform beitritt.',
    oneClickOrdering: 'Bestellen mit einem Klick',
    oneClickDesc: 'Stöbern, vergleichen und bei mehreren Lieferanten in einem Warenkorb bestellen.',
    realTimeTracking: 'Echtzeit-Tracking',
    realTimeDesc: 'Verfolgen Sie jede Bestellung von der Bestätigung bis zur Lieferung.',
    ctaTitle: 'Bereit, Ihre Halal-Lieferkette zu vereinfachen?',
    ctaSubtitle: 'Schließen Sie sich Hunderten von Restaurants an, die mit ProCuro Zeit und Geld sparen.',
    startFree: 'Kostenlos starten',
    learnMore: 'Mehr erfahren',

    // Profile pages
    profilePicture: 'Profilbild',
    editProfile: 'Profil bearbeiten',
    businessDetails: 'Geschäftsdaten',
    accountSettings: 'Kontoeinstellungen',
    languageSprache: 'Sprache / Language',
    changeEmailPassword: 'E-Mail & Passwort ändern',
    updatePhoneNumber: 'Telefonnummer aktualisieren',
    manageMyAddresses: 'Meine Adressen verwalten',
    deleteAccount: 'Konto löschen',
    viewMyOrders: 'Meine Bestellungen',
    viewAnalysis: 'Analyse ansehen',
    mySales: 'Meine Verkäufe',
    restaurant: 'Restaurant',
    supplier: 'Lieferant',
    restaurantOwner: 'Restaurantbesitzer',
    taxIdVat: 'Steuernummer / USt-IdNr.',
    city: 'Stadt',
    cuisineType: 'Küche / Typ',
    categories: 'Kategorien',
    businessLocations: 'Geschäftsstandorte',
    bankDetails: 'Bankdaten',
    add: 'Hinzufügen',
    addAddress: 'Adresse hinzufügen',
    addTaxId: 'Steuernummer hinzufügen',
    addBankDetails: 'Bankdaten hinzufügen',
    notSet: 'Nicht festgelegt',
    saveChanges: 'Änderungen speichern',
    selected: 'ausgewählt',
    locationsHelp: 'Tippen Sie auf jeden Standort, den Sie in Ihrem Profil anzeigen möchten',
    manageAddresses: 'Adressen verwalten',
    cityLocation: 'Stadt / Standort',
    useGps: 'GPS verwenden',
    useMyLocation: 'Meinen Standort verwenden',
    detecting: 'Suche…',
    halal: 'Halal',
    aboutOptional: 'Eine kurze Beschreibung Ihres Restaurants...',
    yourName: 'Ihr Name',
    restaurantName: 'Restaurantname',
    businessName: 'Firmenname',
    description: 'Beschreibung',
    bio: 'Über',
    website: 'Webseite (optional)',
    requiredField: '* Pflichtfeld',

    // AI
    aiInsights: 'KI-Einblicke',
    poweredByGemini: 'Powered by Gemini',
    refreshInsights: 'Einblicke aktualisieren',
    tryAgain: 'Erneut versuchen',
    generateInsights: 'Einblicke generieren',
    analyseYourSales: 'Verkaufsdaten analysieren',
    aiHelpText: 'KI-gestützte Einblicke in Umsatz, Top-Produkte und Wachstumschancen.',

    // Common
    save: 'Speichern',
    cancel: 'Abbrechen',
    close: 'Schließen',
    back: 'Zurück',
    loading: 'Laden…',
    submit: 'Absenden',
    confirm: 'Bestätigen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    search: 'Suchen',
    filter: 'Filter',
    addToCart: 'In den Warenkorb',
    order: 'Bestellung',
    orders: 'Bestellungen',
    products: 'Produkte',
    analytics: 'Analysen',
    settings: 'Einstellungen',
    language: 'Sprache',
    halalCertified: 'Halal-zertifiziert',
    rating: 'Bewertung',
    location: 'Standort',
    phone: 'Telefon',
    email: 'E-Mail',
    address: 'Adresse',

    // Landing page extra
    browseByCategory: 'Nach Kategorie stöbern',
    howItWorks: 'So funktioniert es',
    howItWorksStep1Title: 'Konto erstellen',
    howItWorksStep1Desc: 'Registrieren Sie sich in wenigen Minuten als Restaurantbesitzer oder Lieferant. Keine versteckten Gebühren.',
    howItWorksStep2Title: 'Stöbern & Bestellen',
    howItWorksStep2Desc: 'Stöbern Sie bei verifizierten Halal-Lieferanten und bestellen Sie mit einem Klick.',
    howItWorksStep3Title: 'Lieferung verfolgen',
    howItWorksStep3Desc: 'Verfolgen Sie Ihre Lieferung in Echtzeit und verwalten Sie alle Bestellungen an einem Ort.',
    gdprCompliant: 'DSGVO-konform',
    halalVerifiedBadge: 'Halal-zertifizierte Lieferanten',
    noHiddenFees: 'Keine versteckten Gebühren',
    noProductsFound: 'Keine Produkte gefunden. Werden Sie der erste Lieferant!',
    noSuppliersYet: 'Noch keine verifizierten Lieferanten.',
    outOfStock: 'Nicht verfügbar',
    statsRestaurants: 'Restaurants',
    statsVerifiedSuppliers: 'Geprüfte Lieferanten',
    statsOrdersPlaced: 'Bestellungen',
    statsAverageRating: 'Durchschnittsbewertung',
    catAll: 'Alle',
    catMeat: 'Fleisch',
    catPoultry: 'Geflügel',
    catSeafood: 'Meeresfrüchte',
    catDairy: 'Milchprodukte',
    catVegetables: 'Gemüse',
    catFruits: 'Obst',
    catBakery: 'Backwaren',
    catBeverages: 'Getränke',
    catSpices: 'Gewürze',
    catOther: 'Sonstiges',

    // About page
    aboutTitle: 'Über ProCuro',
    aboutIntro: 'ProCuro ist eine B2B-Halal-Beschaffungsplattform, die zertifizierte Halal-Lieferanten mit Restaurantbesitzern in ganz Deutschland verbindet. Unsere Mission ist es, Halal-Lieferketten transparent, effizient und vertrauenswürdig zu machen.',
    aboutCard1Title: 'Geprüftes Halal',
    aboutCard1Desc: 'Jeder Lieferant auf ProCuro hält eine gültige Halal-Zertifizierung, die von unserem Admin-Team geprüft wurde.',
    aboutCard2Title: 'Gemeinschaft zuerst',
    aboutCard2Desc: 'Entwickelt für die Halal-Geschäftsgemeinschaft in Deutschland — Lieferanten, Restaurantbesitzer und Caterer.',
    aboutCard3Title: 'Made in Germany',
    aboutCard3Desc: 'Hauptsitz in Paderborn, NRW. Vollständig konform mit deutschen und EU-Vorschriften.',
    aboutOurStory: 'Unsere Geschichte',
    aboutStoryP1: 'ProCuro wurde gegründet, um ein echtes Problem zu lösen: Restaurantbesitzer in Deutschland hatten Schwierigkeiten, zuverlässige, zertifizierte Halal-Lieferanten zu finden — und Lieferanten hatten keinen einfachen Weg, ihre Kunden zu erreichen. Wir haben eine Plattform entwickelt, die diese Lücke mit einem nahtlosen Bestellsystem, Echtzeit-Kommunikation und transparenter Zertifizierungsverifizierung überbrückt.',
    aboutStoryP2: 'Heute bedient ProCuro Dutzende von verifizierten Lieferanten und Hunderte von Restaurants in ganz Deutschland, mit Fokus auf Qualität, Vertrauen und Gemeinschaft.',
    contactUs: 'Kontakt',
    aboutLocation: 'Standort: Paderborn, Nordrhein-Westfalen, Deutschland',

    // Careers page
    careersTitle: 'Karriere bei ProCuro',
    careersSubtitle: 'Gestalten Sie mit uns die Zukunft der Halal-Beschaffung in Deutschland.',
    careersWhyTitle: 'Warum ProCuro?',
    careersWhyDesc: 'Wir sind ein mission-orientiertes Startup mit Sitz in Paderborn, NRW, das ein echtes Problem für die Halal-Geschäftsgemeinschaft löst. Wir bieten ein kollaboratives Umfeld, wettbewerbsfähige Gehälter, flexible Arbeitszeiten und die Möglichkeit, einen bedeutenden Beitrag zu leisten.',
    careersOpenPositions: 'Offene Stellen',
    careersApplyEmail: 'Per E-Mail bewerben',
    careersNoRole: 'Keine passende Stelle dabei? Wir freuen uns trotzdem über Ihre Bewerbung.',
    careersSpontaneous: 'Initiativbewerbung senden →',
    careersJob1Title: 'Full-Stack-Entwickler (React / Node.js)',
    careersJob1Type: 'Vollzeit',
    careersJob1Location: 'Paderborn, NRW (Remote möglich)',
    careersJob1Desc: 'Helfen Sie beim Aufbau und der Skalierung unserer Beschaffungsplattform. Erfahrung mit React, Supabase und TypeScript bevorzugt.',
    careersJob2Title: 'Business Development Manager',
    careersJob2Type: 'Vollzeit',
    careersJob2Location: 'Paderborn, NRW',
    careersJob2Desc: 'Fördern Sie Partnerschaften mit Halal-Lieferanten und Restaurantketten in ganz Deutschland. Deutsch und Englisch erforderlich.',
    careersJob3Title: 'Customer Success Specialist',
    careersJob3Type: 'Teilzeit / Vollzeit',
    careersJob3Location: 'Remote (Deutschland)',
    careersJob3Desc: 'Unterstützen Sie unsere wachsende Lieferanten- und Restaurantbesitzer-Community. Fließendes Deutsch erforderlich.',

    // Press page
    pressTitle: 'Presse & Medien',
    pressSubtitle: 'Informationen und Ressourcen für Journalisten und Medienschaffende.',
    pressAboutTitle: 'Über ProCuro',
    pressAboutDesc: 'ProCuro ist Deutschlands führende B2B-Halal-Beschaffungsplattform, die zertifizierte Halal-Lieferanten mit Restaurantbesitzern und Caterern verbindet. Gegründet in Paderborn, NRW, bringt ProCuro Transparenz, Vertrauen und Effizienz in Halal-Lieferketten in ganz Deutschland.',
    pressKeyFacts: 'Fakten',
    pressFoundedLabel: 'Gegründet',
    pressHQLabel: 'Hauptsitz',
    pressMarketLabel: 'Markt',
    pressPlatformLabel: 'Plattform',
    pressLanguagesLabel: 'Sprachen',
    pressMarketValue: 'B2B Halal Lebensmittelbeschaffung, Deutschland',
    pressPlatformValue: 'Web-basiertes SaaS (React / Supabase)',
    pressLanguagesValue: 'Deutsch, Englisch, Arabisch (geplant)',
    pressContactTitle: 'Pressekontakt',
    pressContactDesc: 'Für Presseanfragen, Interviewanfragen oder Medienmaterial wenden Sie sich bitte an unser Team.',
    pressContactButton: 'Presseteam kontaktieren',
    pressBrandAssetsTitle: 'Marken-Assets',
    pressBrandAssetsDesc: 'Logo-Dateien, Markenrichtlinien und hochauflösende Bilder auf Anfrage erhältlich. Schreiben Sie uns an support@procuro.com.',
    pressStatRestaurants: 'Restaurants',
    pressStatSuppliers: 'Lieferanten',
    pressStatRating: 'Plattformbewertung',

    // Help Center page
    helpTitle: 'Hilfezentrum',
    helpSubtitle: 'Haben Sie eine Frage oder ein Problem? Füllen Sie das Formular aus und wir melden uns innerhalb von 24 Stunden.',
    helpNameLabel: 'Name *',
    helpNamePlaceholder: 'Ihr Name',
    helpEmailPlaceholder: 'sie@beispiel.de',
    helpTopicLabel: 'Thema',
    helpTopicPlaceholder: 'Thema wählen...',
    helpMessageLabel: 'Nachricht *',
    helpMessagePlaceholder: 'Beschreiben Sie Ihr Anliegen ausführlich...',
    helpSendMessage: 'Nachricht senden',
    helpEmailDirect: 'Oder schreiben Sie uns direkt an',
    helpSentTitle: 'Nachricht gesendet!',
    helpSentDesc: 'Ihr E-Mail-Programm sollte sich geöffnet haben. Falls nicht, schreiben Sie uns direkt an',
    helpRequiredError: 'Bitte füllen Sie alle Pflichtfelder aus',
    helpTopicAccount: 'Konto & Registrierung',
    helpTopicOrders: 'Bestellungen & Lieferung',
    helpTopicPayments: 'Zahlungen & Rechnungen',
    helpTopicHalal: 'Halal-Zertifizierung',
    helpTopicTechnical: 'Technisches Problem',
    helpTopicOther: 'Sonstiges',

    // Legal pages
    privacyTitle: 'Datenschutzerklärung',
    privacySubtitle: 'Zuletzt aktualisiert: Mai 2025',
    privacyLegalNote: '',
    termsTitle: 'Allgemeine Geschäftsbedingungen',
    termsSubtitle: 'Stand: Mai 2025',
    termsLegalNote: '',

    // Sidebar navigation
    navStore: 'Shop',
    navCart: 'Warenkorb',
    navOrders: 'Bestellungen',
    navAnalytics: 'Analysen',
    navMessages: 'Nachrichten',
    navProfile: 'Profil',
    navDashboard: 'Dashboard',
    navProducts: 'Produkte',

    // Notifications
    notifications: 'Benachrichtigungen',
    markAllRead: 'Alle gelesen',
    noNotificationsYet: 'Noch keine Benachrichtigungen',

    // Footer
    footerCompany: 'Unternehmen',
    footerResources: 'Ressourcen',
    footerContact: 'Kontakt',
    footerAboutUs: 'Über uns',
    footerCareers: 'Karriere',
    footerPress: 'Presse',
    footerHelpCenter: 'Hilfezentrum',
    footerPrivacyPolicy: 'Datenschutz',
    footerTermsOfService: 'AGB',
    footerCopyright: '© 2026 ProCuro GmbH. Alle Rechte vorbehalten.',
    footerTagline: 'Halal-Unternehmen mit nahtloser Beschaffung und Lagerverwaltung in ganz Deutschland stärken.',

    // Store / Products
    categoriesLabel: 'Kategorien',
    recommendedSuppliers: 'Empfohlene Lieferanten',
    recommendedOrders: 'Empfohlene Bestellungen',
    seeAll: 'Alle anzeigen',
    allProductsTitle: 'Alle Produkte',
    allSuppliersTitle: 'Alle Lieferanten',
    nearMe: 'In der Nähe',
    sortLabel: 'Sortieren',
    filterLabel: 'Filter',
    sortRecommended: 'Empfohlen',
    sortPriceAsc: 'Preis: Aufsteigend',
    sortPriceDesc: 'Preis: Absteigend',
    sortNameAZ: 'Name A–Z',
    sortTopRated: 'Bestbewertet',
    searchProductsPlaceholder: 'Halal-Produkte suchen...',
    searchSuppliersPlaceholder: 'Lieferanten nach Name oder Stadt suchen...',
    outOfStockText: 'Nicht verfügbar',
    clearFilters: 'Filter zurücksetzen',
    noProductsFoundSearch: 'Keine Produkte gefunden',
    noSuppliersFound: 'Keine Lieferanten gefunden',
    pendingReview: 'Prüfung ausstehend',
    halalCertifiedBadge: 'Halal-zertifiziert',
    completeProfileBtn: 'Profil vervollständigen',
    completeProfileWarning: 'Vervollständigen Sie Ihr Profil, um Bestellungen aufzugeben',
    missingLabel: 'Fehlend',
    allowLocation: 'Erlauben',
    allowLocationTitle: 'Standort für genaue Liefergebühren erlauben',
    locationDesc: 'Wir nutzen Ihren Standort, um die Liefergebühr von jedem Lieferanten zu berechnen.',
    locationBlocked: 'Standort in Browsereinstellungen gesperrt',
    locationBlockedDesc: 'Aktivieren Sie den Standort für diese Website in Ihren Browsereinstellungen oder geben Sie Ihre Adresse manuell in Ihrem Profil ein.',
    addManually: 'Manuell hinzufügen',
    noSuppliersYetStore: 'Noch keine Lieferanten.',

    // Orders
    placedOrders: 'Aufgegebene Bestellungen',
    ordersOngoing: 'Laufend',
    ordersCompleted: 'Abgeschlossen',
    noOrdersYet: 'Noch keine Bestellungen.',
    unitPrice: 'Einzelpreis',
    qtyOrdered: 'Bestellmenge',
    subtotalText: 'Zwischensumme',
    downloadInvoice: 'Rechnung herunterladen',
    cancelOrder: 'Bestellung stornieren',
    confirmDelivery: 'Lieferung bestätigen',
    orderFrom: 'Bestellung von',
    viewDetails: 'Details anzeigen',
    backToOrders: 'Zurück zu Bestellungen',
    cancellationReason: 'Stornogrund',
    refundReceipt: 'Rückzahlungsbeleg',
    disputeDelivery: 'Lieferung anfechten',
    rateOrder: 'Bestellung bewerten',
    orderItems: 'Bestellpositionen',
    paymentMethod: 'Zahlungsmethode',
    deliveryFee: 'Liefergebühr',
    totalAmount: 'Gesamtbetrag',
    orderNote: 'Anmerkung',

    // Cart
    cartTitle: 'Ihr Warenkorb',
    cartEmpty: 'Ihr Warenkorb ist leer',
    cartEmptyDesc: 'Stöbern Sie bei unseren verifizierten Halal-Lieferanten',
    browseStore: 'Shop durchsuchen',
    reviewOrder: 'Bestellung prüfen',
    paymentLabel: 'Zahlungsmethode',
    orderPlaced: 'Bestellung aufgegeben!',
    bankTransfer: 'Banküberweisung',
    cashOnDelivery: 'Barzahlung bei Lieferung',
    deliveryAddress: 'Lieferadresse',
    placeOrderBtn: 'Bestellen',
    continueShopping: 'Weiter einkaufen',
    cartStep1: 'Warenkorb',
    cartStep2: 'Zahlung',
    cartStep3: 'Fertig',

    // Supplier profile (public)
    supplierProducts: 'Produkte',
    supplierAbout: 'Über',
    supplierCertifications: 'Zertifizierungen',
    supplierLocations: 'Standorte',
    orderFromSupplier: 'Bei diesem Lieferanten bestellen',
    messageSupplier: 'Lieferant kontaktieren',
    reportSupplier: 'Lieferant melden',
    noProductsListed: 'Noch keine Produkte',
    noCertificatesAvailable: 'Keine Zertifikate vorhanden',
    noDescriptionProvided: 'Keine Beschreibung vorhanden',
    showLess: 'Weniger anzeigen',
    seeAllProducts: 'Alle anzeigen',
    verified: 'Verifiziert',
    shareProfile: 'Teilen',

    // Account deleted page
    accountDeletedTitle: 'Auf Wiedersehen & Danke',
    accountDeletedSubtitle: 'Ihr Konto wurde gelöscht',
    accountDeletedMessage: 'Es tut uns sehr leid, Sie gehen zu sehen. Es war uns eine Ehre, Teil Ihrer Reise zu sein, und wir hoffen, dass ProCuro Ihre Arbeit ein wenig leichter gemacht hat. Wir wünschen Ihnen alles Gute und viel Erfolg für alles, was noch kommt — Sie sind jederzeit herzlich willkommen, zurückzukehren. 🌙',
    accountDeletedThanks: 'Vielen Dank, dass Sie Teil der ProCuro-Familie waren. Wir sind dankbar für das Vertrauen, das Sie uns entgegengebracht haben. ✨💙',
    accountDeletedCta: 'Zur Startseite',

    // Login / auth
    loginTagline: 'Die Halal-Beschaffungsplattform',
    emailAddressLabel: 'E-Mail-Adresse',
    passwordLabel: 'Passwort',
    forgotPassword: 'Passwort vergessen?',
    loggingIn: 'Anmelden...',
    orContinueWith: 'ODER WEITER MIT',
    dontHaveAccount: 'Noch kein Konto?',
    forgotPasswordTitle: 'Passwort vergessen?',
    forgotPasswordDesc: 'Geben Sie Ihre E-Mail ein und wir senden Ihnen einen Reset-Link.',
    backToLoginBtn: '← Zurück zur Anmeldung',
    sendResetLink: 'Reset-Link senden',
    sending: 'Senden...',
    checkYourEmail: 'E-Mail überprüfen',
    resetLinkSentTo: 'Wir haben einen Passwort-Reset-Link gesendet an:',
    resetLinkExpiry: 'Klicken Sie auf den Link in der E-Mail, um ein neues Passwort festzulegen. Der Link läuft in 1 Stunde ab.',

    // Register
    createFreeAccount: 'Kostenloses Konto erstellen',
    fullNameLabel: 'Vollständiger Name',
    passwordStrengthLabel: 'Stärke',
    pwStrengthWeak: 'Schwach',
    pwStrengthGood: 'Mittel',
    pwStrengthStrong: 'Stark',
    pwReqLength: 'Mehr als 8 Zeichen',
    pwReqUppercase: 'Ein Großbuchstabe',
    pwReqSpecial: 'Sonderzeichen (@#$%...)',
    confirmPasswordLabel: 'Passwort bestätigen',
    createAccountBtn: 'Konto erstellen',
    creatingAccount: 'Konto wird erstellt...',
    passwordsNoMatch: 'Passwörter stimmen nicht überein',
    passwordTooShort: 'Passwort muss mindestens 6 Zeichen haben',
    alreadyHaveAccount: 'Bereits ein Konto?',

    // Select role
    welcomeToProcuro: 'Willkommen bei ProCuro!',
    accountReadyDesc: 'Ihr Konto ist bereit. Wählen Sie nun, wie Sie ProCuro nutzen möchten.',
    choiceIsPermanent: 'Diese Wahl ist dauerhaft und kann nicht geändert werden.',
    roleOwnerDesc: 'Durchsuchen und bestellen Sie bei verifizierten Halal-Lieferanten',
    roleSupplierDesc: 'Verkaufen Sie Ihre Halal-Produkte an Restaurants in ganz Deutschland',
    settingUpAccount: 'Konto wird eingerichtet...',

    // Navbar address form
    newAddress: 'Neue Adresse',
    labelFieldPlaceholder: 'Bezeichnung (z. B. Restaurant)',
    streetFieldPlaceholder: 'Straße *',
    postalFieldPlaceholder: 'PLZ',
    cityFieldPlaceholder: 'Stadt *',

    // AddToCartModal
    calculatingDeliveryFee: 'Liefergebühr wird berechnet…',
    addAddressForDelivery: 'Adresse hinzufügen, um die Liefergebühr zu sehen',
    deliveryFeeUnavailable: 'Liefergebühr nicht verfügbar',
    freeDelivery: 'Kostenlose Lieferung',
    deliveryLabelText: 'Lieferung:',
    quantity: 'Menge',
    discountCode: 'Rabattcode',
    apply: 'Anwenden',
    currentlyOutOfStock: 'Derzeit nicht auf Lager',
    unavailable: 'Nicht verfügbar',
    reportThisProduct: 'Produkt melden',
    discountApplied: '10% Rabatt angewendet!',
    discountInvalid: 'Code ist falsch',
    perUnit: 'pro',

    // Orders (owner)
    myOrders: 'Meine Bestellungen',
    ongoingOrdersTab: 'Laufende Bestellungen',
    completedOrdersTab: 'Abgeschlossene Bestellungen',
    orderDetailsTitle: 'Bestelldetails',
    orderIdLabel: 'Bestellnummer',
    dateLabel: 'Datum',
    supplierNameLabel: 'Lieferant',
    itemsOrderedLabel: 'Bestellte Artikel',
    totalLabel: 'Gesamt',
    cancellationPendingTitle: 'Stornierung ausstehend',
    cancellationPendingDesc: 'Ihre Stornierungsanfrage wurde an den Lieferanten gesendet. Sie wird geprüft und die Erstattung bearbeitet.',
    orderCancelledTitle: 'Bestellung storniert',
    cancelledBySupplierText: 'vom Lieferanten',
    cancelledByYouText: 'von Ihnen',
    refundReceiptUploadedTitle: 'Erstattungsbeleg hochgeladen',
    refundReceiptUploadedDesc: 'Der Lieferant hat einen Erstattungsnachweis hochgeladen. Bitte prüfen und bestätigen Sie unten.',
    confirmRefundReceivedBtn: 'Erstattungseingang bestätigen',
    viewRefundReceiptLink: 'Erstattungsbeleg anzeigen',
    disputePendingTitle: 'Streitfall ausstehend',
    disputePendingDesc: 'Ihr Bericht wurde an den Lieferanten gesendet. Sie werden in Kürze antworten.',
    disputeResolutionTitle: 'Streitfall-Lösung',
    suppliersResponseLabel: 'Antwort des Lieferanten:',
    markAsDeliveredBtn: 'Als geliefert markieren',
    didntReceiveItBtn: 'Ich habe es nicht erhalten',
    chatWithSupplierBtn: 'Mit Lieferanten chatten',
    reportThisOrder: 'Bestellung melden',
    markDeliveredBtn: 'Als geliefert markieren',
    confirmRefundBtn: 'Erstattung bestätigen',
    requestCancellationBtn: 'Stornierung beantragen',
    keepOrderBtn: 'Bestellung behalten',
    reportNonDeliveryTitle: 'Nichtlieferung melden',
    reportNonDeliveryDesc: 'Der Lieferant wird benachrichtigt und gebeten zu antworten. Bitte schildern Sie, was passiert ist.',
    reasonRequiredLabel: 'Grund *',
    whatHappenedPlaceholder: 'Was ist passiert?',
    sendReport: 'Bericht senden',
    cancelOrderTitle: 'Bestellung stornieren',
    reasonForCancellationLabel: 'Stornierungsgrund *',
    cancelReasonPlaceholder: 'z. B. Meinung geändert, versehentlich bestellt, anderen Lieferanten gefunden...',
    bankTransferCancelNote: 'Ihre Stornierung wird zur Überprüfung an den Lieferanten gesendet. Nach Zustimmung wird er einen Zahlungsnachweis hochladen.',
    bankTransferOrderLabel: 'Banküberweisung',
    disputePendingAwaitSupplier: 'Streitfall ausstehend — Antwort des Lieferanten wird erwartet',
    ratingOrderDelivered: 'Bestellung geliefert!',
    ratingHowWouldYouRate: 'Wie würden Sie bewerten',
    ratingPoor: 'Schlecht',
    ratingFair: 'Ausreichend',
    ratingGoodLabel: 'Gut',
    ratingVeryGood: 'Sehr gut',
    ratingExcellent: 'Ausgezeichnet',
    skipBtn: 'Überspringen',
    submitRating: 'Bewertung abgeben',
    noTabOrders: 'Keine Bestellungen',
    cancelledPendingLabel: 'Stornierung ausstehend:',
    cancelledBySupplierLabel: 'Vom Lieferanten storniert:',
    cancelledByYouLabel: 'Von Ihnen storniert:',
    disputeResolvedLabel: 'Streitfall gelöst:',

    // Supplier Orders
    uploadRefundProof: 'Erstattungsnachweis hochladen (Bild oder PDF)',
    selectRefundReceipt: 'Erstattungsbeleg auswählen',
    uploadAndNotifyOwner: 'Hochladen & Besitzer benachrichtigen',
    bankTransferRefundRequired: 'Banküberweisung-Erstattung erforderlich',
    viewPaymentReceipt: 'Zahlungsbeleg anzeigen',
    respondToDisputeTitle: 'Auf Lieferstreit reagieren',
    ownersMessageLabel: 'Nachricht des Besitzers:',
    chooseResolution: 'Lösung wählen',
    resendOrder: 'Bestellung erneut senden',
    respondToDisputeBtn: 'Streitfall beantworten',
    chatWithOwnerBtn: 'Mit Besitzer chatten',
    datePlacedLabel: 'Bestelldatum',
    statusLabel: 'Status',
    cancellationRequestedByOwner: 'Stornierung vom Besitzer angefragt',
    ownerWantsCancelNote: 'Der Restaurantbesitzer möchte diese Bestellung stornieren.',
    paidViaBankTransferCancelNote: 'Per Banküberweisung bezahlt — laden Sie unten den Erstattungsnachweis hoch, um diese Stornierung anzunehmen.',
    cancelledByLabel: 'Storniert von:',
    waitingForOwnerReceipt: 'Warte auf Zahlungsbeleg des Restaurantbesitzers',
    outForDeliveryBtn: 'Als „Unterwegs" markieren',
    confirmOrderBtn: 'Bestellung bestätigen',
    refundReceiptUploadedMsg: 'Erstattungsbeleg hochgeladen',
    waitingOwnerConfirmRefund: 'Warte auf Bestätigung des Restaurantbesitzers.',
    noDeliveryAddress: 'Keine Lieferadresse hinterlegt',
    ownerReportedDeliveryDispute: 'Besitzer meldet Nichtlieferung',
    deliveryNotReceived: 'Lieferung nicht erhalten',
    ownerReportedNonDelivery: 'Der Restaurantbesitzer meldet, dass die Bestellung nicht angekommen ist. Sie müssen antworten.',
    ownersReasonLabel: 'Grund des Besitzers',
    deliveryToLabel: 'Lieferung an',
    acceptBtn: 'Annehmen',
    rejectBtn: 'Ablehnen',
    addProductBtn: 'Produkt hinzufügen',
    editProductBtn: 'Produkt bearbeiten',
    addNewProductBtn: 'Neues Produkt hinzufügen',
    noProductsYetSupplier: 'Noch keine Produkte',
    addFirstProduct: 'Erstes Produkt hinzufügen',
    deliveryFeeStructure: 'Liefergebührenstruktur',
    distanceLabel: 'Entfernung',
    productLabel: 'Produkt',
    categoryLabel: 'Kategorie',
    priceLabel: 'Preis',

    // Analytics charts
    spendPeriod: 'Ausgaben (Zeitraum)',
    ordersPeriodLabel: 'Bestellungen (Zeitraum)',
    topCategoryLabel: 'Top-Kategorie',
    topProductLabel: 'Top-Produkt',
    spendingTrend: 'Ausgabentrend',
    topProductsOrdered: 'Meistbestellte Produkte',
    spendingByCategory: 'Ausgaben nach Kategorie',
    topCategoriesEur: 'Top-Kategorien (€)',
    noDataForPeriod: 'Keine Daten für diesen Zeitraum',
    revenueTrend: 'Umsatztrend',
    revenueByProduct: 'Umsatz nach Produkt',
    salesByProductPct: 'Verkäufe nach Produkt (%)',
    topRestaurantClients: 'Top-Restaurantkunden',
    revenueStatLabel: 'Umsatz',
    ordersStatLabel: 'Bestellungen',
    bestProductStatLabel: 'Bestes Produkt',
    activeProductsStatLabel: 'Aktive Produkte',

    // Account banned
    accountBannedBanner: 'Ihr Konto wurde gesperrt. Kontaktieren Sie den Support.',
    accountBannedTitle: 'Konto gesperrt',
    accountBannedContent: 'Ihr Konto wurde von einem Administrator gesperrt. Nur der Chat steht Ihnen zur Kontaktaufnahme mit dem Support zur Verfügung.',

    // Supplier banned (visible to restaurant owners)
    supplierBannedTitle: 'Dieser Lieferant ist gesperrt',
    supplierBannedBanner: 'Dieser Lieferant wurde von einem Administrator wegen Verstoßes gegen unsere Nutzungsbedingungen gesperrt. Sie können keine neuen Bestellungen aufgeben, das Profil und frühere Bestellungen bleiben aber einsehbar.',
    supplierBannedShort: 'Gesperrt',
    supplierBannedChatNotice: 'Das Konto dieses Lieferanten wurde gesperrt. Frühere Bestellungen bleiben einsehbar, neue Bestellungen sind nicht möglich.',
    supplierBannedCartNotice: 'Dieser Lieferant wurde gesperrt. Bitte entfernen Sie seine Artikel, um mit der Kasse fortzufahren.',
    supplierBannedCannotAdd: 'Hinzufügen nicht möglich — Lieferant gesperrt',

    // Owner banned (visible to suppliers)
    ownerBannedTitle: 'Dieses Restaurant-Konto ist gesperrt',
    ownerBannedBanner: 'Dieser Restaurantbesitzer wurde von einem Administrator wegen Verstoßes gegen unsere Nutzungsbedingungen gesperrt. Frühere Bestellungen bleiben sichtbar, neue Bestellungen sind nicht mehr möglich.',
    ownerBannedShort: 'Gesperrt',
    ownerBannedChatNotice: 'Das Konto dieses Restaurantbesitzers wurde gesperrt. Frühere Bestellungen bleiben einsehbar, neue Bestellungen sind nicht möglich.',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('procuro_lang') || 'en' } catch { return 'en' }
  })

  function setLanguage(l) {
    if (!LANGS.includes(l)) return
    setLang(l)
    try { localStorage.setItem('procuro_lang', l) } catch {}
    try { document.documentElement.lang = l } catch {}
  }

  function t(key) {
    return T[lang]?.[key] ?? T.en?.[key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
