import { createContext, useContext, useState } from 'react'

const LanguageContext = createContext()

export const LANGS = ['en', 'de']

const T = {
  en: {
    // Navbar
    logIn: 'Log In',
    signUp: 'Sign Up',
    signOut: 'Sign out',
    profile: 'Profile',
    deliveredTo: 'Delivered to',
    selectAddress: 'Select Address',
    savedAddresses: 'Saved Addresses',
    addNewAddress: 'Add New Address',

    // Landing page
    heroTagline: 'Halal Certified Suppliers Only',
    heroTitle: 'The Smarter Way to Stock Your Halal Kitchen',
    heroSubtitle: 'Connect with verified Halal suppliers. Order everything your restaurant needs in one place. Track, manage, and optimize — all from ProCuro.',
    getStarted: 'Get Started Free',
    browseSuppliers: 'Browse Suppliers',
    trustedBy: 'Trusted by Halal restaurants across Germany',
    featuredSuppliers: 'Featured Suppliers',
    viewAll: 'View All',
    viewAllSuppliers: 'View All Suppliers',
    featuredProducts: 'Featured Products',
    whyProcuro: 'Why ProCuro?',
    whySubtitle: 'Everything you need to run a modern Halal kitchen',
    verifiedHalal: 'Verified Halal Suppliers',
    verifiedHalalDesc: 'Every supplier is manually reviewed and Halal-certified before joining the platform.',
    oneClickOrdering: 'One-Click Ordering',
    oneClickDesc: 'Browse, compare, and order from multiple suppliers in a single cart.',
    realTimeTracking: 'Real-Time Tracking',
    realTimeDesc: 'Track every order from confirmation to delivery — no more chasing suppliers.',
    ctaTitle: 'Ready to simplify your Halal supply chain?',
    ctaSubtitle: 'Join hundreds of restaurants already saving time and money with ProCuro.',
    startFree: 'Start for Free',
    learnMore: 'Learn More',

    // Profile pages
    profilePicture: 'Profile Picture',
    editProfile: 'Edit Profile',
    businessDetails: 'Business Details',
    accountSettings: 'Account Settings',
    languageSprache: 'Language / Sprache',
    changeEmailPassword: 'Change Email & Password',
    updatePhoneNumber: 'Update Phone Number',
    manageMyAddresses: 'Manage My Addresses',
    deleteAccount: 'Delete Account',
    viewMyOrders: 'View My Orders',
    viewAnalysis: 'View Analysis',
    mySales: 'My Sales',
    restaurant: 'Restaurant',
    supplier: 'Supplier',
    restaurantOwner: 'Restaurant Owner',
    taxIdVat: 'Tax ID / VAT',
    city: 'City',
    cuisineType: 'Cuisine / Type',
    categories: 'Categories',
    businessLocations: 'Business Locations',
    bankDetails: 'Bank Details',
    add: 'Add',
    addAddress: 'Add address',
    addTaxId: 'Add Tax ID',
    addBankDetails: 'Add bank details',
    notSet: 'Not set',
    saveChanges: 'Save Changes',
    selected: 'selected',
    locationsHelp: 'Tap each location you want shown on your profile',
    manageAddresses: 'Manage Addresses',
    cityLocation: 'City / Location',
    useGps: 'Use GPS',
    useMyLocation: 'Use My Location',
    detecting: 'Detecting…',
    halal: 'Halal',
    aboutOptional: 'A short description about your restaurant...',
    yourName: 'Your Name',
    restaurantName: 'Restaurant Name',
    businessName: 'Business Name',
    description: 'Description',
    bio: 'About',
    website: 'Website (optional)',
    requiredField: '* Required',

    // AI
    aiInsights: 'AI Insights',
    poweredByGemini: 'Powered by Gemini',
    refreshInsights: 'Refresh insights',
    tryAgain: 'Try again',
    generateInsights: 'Generate Insights',
    analyseYourSales: 'Analyse your sales data',
    aiHelpText: 'Get AI-powered insights on revenue, top products, and growth opportunities.',

    // Common
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    back: 'Back',
    loading: 'Loading…',
    submit: 'Submit',
    confirm: 'Confirm',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search',
    filter: 'Filter',
    addToCart: 'Add to Cart',
    order: 'Order',
    orders: 'Orders',
    products: 'Products',
    analytics: 'Analytics',
    settings: 'Settings',
    language: 'Language',
    halalCertified: 'Halal Certified',
    rating: 'Rating',
    location: 'Location',
    phone: 'Phone',
    email: 'Email',
    address: 'Address',

    // Landing page extra
    browseByCategory: 'Browse by Category',
    howItWorks: 'How It Works',
    howItWorksStep1Title: 'Create Your Account',
    howItWorksStep1Desc: 'Sign up as a restaurant owner or supplier in minutes. No hidden fees.',
    howItWorksStep2Title: 'Browse & Order',
    howItWorksStep2Desc: 'Browse verified Halal suppliers and place orders with a single click.',
    howItWorksStep3Title: 'Track Delivery',
    howItWorksStep3Desc: 'Track your delivery in real-time and manage all orders from one place.',
    gdprCompliant: 'GDPR Compliant',
    halalVerifiedBadge: 'Halal Verified Suppliers',
    noHiddenFees: 'No Hidden Fees',
    noProductsFound: 'No products found. Be the first supplier to list products!',
    noSuppliersYet: 'No verified suppliers yet.',
    outOfStock: 'Out of Stock',
    statsRestaurants: 'Restaurants',
    statsVerifiedSuppliers: 'Verified Suppliers',
    statsOrdersPlaced: 'Orders Placed',
    statsAverageRating: 'Average Rating',
    catAll: 'All',
    catMeat: 'Meat',
    catPoultry: 'Poultry',
    catSeafood: 'Seafood',
    catDairy: 'Dairy',
    catVegetables: 'Vegetables',
    catFruits: 'Fruits',
    catBakery: 'Bakery',
    catBeverages: 'Beverages',
    catSpices: 'Spices',
    catOther: 'Other',

    // About page
    aboutTitle: 'About ProCuro',
    aboutIntro: 'ProCuro is a B2B Halal procurement platform connecting verified Halal suppliers with restaurant owners across Germany. Our mission is to make Halal supply chains transparent, efficient, and trustworthy.',
    aboutCard1Title: 'Verified Halal',
    aboutCard1Desc: 'Every supplier on ProCuro holds a valid Halal certification reviewed by our admin team.',
    aboutCard2Title: 'Community First',
    aboutCard2Desc: 'Built for the Halal business community in Germany — suppliers, restaurant owners, and caterers.',
    aboutCard3Title: 'Made in Germany',
    aboutCard3Desc: 'Headquartered in Paderborn, NRW. Fully compliant with German and EU regulations.',
    aboutOurStory: 'Our Story',
    aboutStoryP1: 'ProCuro was founded to solve a real problem: restaurant owners in Germany struggled to find reliable, certified Halal suppliers — and suppliers had no easy way to reach their customers. We built a platform that bridges this gap with a seamless ordering system, real-time communication, and transparent certification verification.',
    aboutStoryP2: 'Today, ProCuro serves dozens of verified suppliers and hundreds of restaurants across Germany, with a focus on quality, trust, and community.',
    contactUs: 'Contact Us',
    aboutLocation: 'Location: Paderborn, North Rhine-Westphalia, Germany',

    // Careers page
    careersTitle: 'Careers at ProCuro',
    careersSubtitle: 'Join us in building the future of Halal procurement in Germany.',
    careersWhyTitle: 'Why ProCuro?',
    careersWhyDesc: "We're a mission-driven startup based in Paderborn, NRW, solving a real problem for the Halal business community. We offer a collaborative environment, competitive salaries, flexible working arrangements, and the chance to make a meaningful impact.",
    careersOpenPositions: 'Open Positions',
    careersApplyEmail: 'Apply via Email',
    careersNoRole: "Don't see your role? We'd still love to hear from you.",
    careersSpontaneous: 'Send a spontaneous application →',
    careersJob1Title: 'Full-Stack Developer (React / Node.js)',
    careersJob1Type: 'Full-Time',
    careersJob1Location: 'Paderborn, NRW (Remote-friendly)',
    careersJob1Desc: 'Help build and scale our procurement platform. Experience with React, Supabase, and TypeScript preferred.',
    careersJob2Title: 'Business Development Manager',
    careersJob2Type: 'Full-Time',
    careersJob2Location: 'Paderborn, NRW',
    careersJob2Desc: 'Drive partnerships with Halal suppliers and restaurant chains across Germany. German and English required.',
    careersJob3Title: 'Customer Success Specialist',
    careersJob3Type: 'Part-Time / Full-Time',
    careersJob3Location: 'Remote (Germany)',
    careersJob3Desc: 'Support our growing supplier and restaurant owner community. Fluent German required.',

    // Press page
    pressTitle: 'Press & Media',
    pressSubtitle: 'Information and resources for journalists and media professionals.',
    pressAboutTitle: 'About ProCuro',
    pressAboutDesc: "ProCuro is Germany's leading B2B Halal procurement platform, connecting verified Halal suppliers with restaurant owners and caterers. Founded in Paderborn, NRW, ProCuro brings transparency, trust, and efficiency to Halal supply chains across Germany.",
    pressKeyFacts: 'Key Facts',
    pressFoundedLabel: 'Founded',
    pressHQLabel: 'HQ',
    pressMarketLabel: 'Market',
    pressPlatformLabel: 'Platform',
    pressLanguagesLabel: 'Languages',
    pressMarketValue: 'B2B Halal food procurement, Germany',
    pressPlatformValue: 'Web-based SaaS (React / Supabase)',
    pressLanguagesValue: 'German, English, Arabic (planned)',
    pressContactTitle: 'Press Contact',
    pressContactDesc: 'For press inquiries, interview requests, or media assets, please reach out to our team.',
    pressContactButton: 'Contact Press Team',
    pressBrandAssetsTitle: 'Brand Assets',
    pressBrandAssetsDesc: 'Logo files, brand guidelines, and high-res images available on request. Email us at support@procuro.com.',
    pressStatRestaurants: 'Restaurants',
    pressStatSuppliers: 'Suppliers',
    pressStatRating: 'Platform Rating',

    // Help Center page
    helpTitle: 'Help Center',
    helpSubtitle: "Have a question or issue? Fill out the form below and we'll get back to you within 24 hours.",
    helpNameLabel: 'Name *',
    helpNamePlaceholder: 'Your name',
    helpEmailPlaceholder: 'you@example.com',
    helpTopicLabel: 'Topic',
    helpTopicPlaceholder: 'Select a topic...',
    helpMessageLabel: 'Message *',
    helpMessagePlaceholder: 'Describe your issue in detail...',
    helpSendMessage: 'Send Message',
    helpEmailDirect: 'Or email us directly at',
    helpSentTitle: 'Message sent!',
    helpSentDesc: 'Your email client should have opened. If not, email us directly at',
    helpRequiredError: 'Please fill in all required fields',
    helpTopicAccount: 'Account & Registration',
    helpTopicOrders: 'Orders & Delivery',
    helpTopicPayments: 'Payments & Invoicing',
    helpTopicHalal: 'Halal Certification',
    helpTopicTechnical: 'Technical Issue',
    helpTopicOther: 'Other',

    // Legal pages
    privacyTitle: 'Privacy Policy',
    privacySubtitle: 'Last updated: May 2025',
    privacyLegalNote: 'This privacy policy (Datenschutzerklärung) is provided in German as required by GDPR/DSGVO. For an English summary, contact us at support@procuro.com.',
    termsTitle: 'Terms of Service',
    termsSubtitle: 'Effective: May 2025',
    termsLegalNote: 'Our Terms of Service (Allgemeine Geschäftsbedingungen) are in German as required by German law. For an English summary, contact us at support@procuro.com.',
  },
  de: {
    // Navbar
    logIn: 'Anmelden',
    signUp: 'Registrieren',
    signOut: 'Abmelden',
    profile: 'Profil',
    deliveredTo: 'Lieferung an',
    selectAddress: 'Adresse wählen',
    savedAddresses: 'Gespeicherte Adressen',
    addNewAddress: 'Neue Adresse hinzufügen',

    // Landing page
    heroTagline: 'Nur Halal-zertifizierte Lieferanten',
    heroTitle: 'Der clevere Weg, Ihre Halal-Küche zu versorgen',
    heroSubtitle: 'Verbinden Sie sich mit geprüften Halal-Lieferanten. Bestellen Sie alles, was Ihr Restaurant braucht, an einem Ort. Verfolgen, verwalten und optimieren — alles mit ProCuro.',
    getStarted: 'Kostenlos starten',
    browseSuppliers: 'Lieferanten entdecken',
    trustedBy: 'Vertraut von Halal-Restaurants in ganz Deutschland',
    featuredSuppliers: 'Empfohlene Lieferanten',
    viewAll: 'Alle anzeigen',
    viewAllSuppliers: 'Alle Lieferanten anzeigen',
    featuredProducts: 'Empfohlene Produkte',
    whyProcuro: 'Warum ProCuro?',
    whySubtitle: 'Alles, was Sie für eine moderne Halal-Küche brauchen',
    verifiedHalal: 'Geprüfte Halal-Lieferanten',
    verifiedHalalDesc: 'Jeder Lieferant wird manuell geprüft und Halal-zertifiziert, bevor er der Plattform beitritt.',
    oneClickOrdering: 'Bestellen mit einem Klick',
    oneClickDesc: 'Stöbern, vergleichen und bei mehreren Lieferanten in einem Warenkorb bestellen.',
    realTimeTracking: 'Echtzeit-Tracking',
    realTimeDesc: 'Verfolgen Sie jede Bestellung von der Bestätigung bis zur Lieferung.',
    ctaTitle: 'Bereit, Ihre Halal-Lieferkette zu vereinfachen?',
    ctaSubtitle: 'Schließen Sie sich Hunderten von Restaurants an, die mit ProCuro Zeit und Geld sparen.',
    startFree: 'Kostenlos starten',
    learnMore: 'Mehr erfahren',

    // Profile pages
    profilePicture: 'Profilbild',
    editProfile: 'Profil bearbeiten',
    businessDetails: 'Geschäftsdaten',
    accountSettings: 'Kontoeinstellungen',
    languageSprache: 'Sprache / Language',
    changeEmailPassword: 'E-Mail & Passwort ändern',
    updatePhoneNumber: 'Telefonnummer aktualisieren',
    manageMyAddresses: 'Meine Adressen verwalten',
    deleteAccount: 'Konto löschen',
    viewMyOrders: 'Meine Bestellungen',
    viewAnalysis: 'Analyse ansehen',
    mySales: 'Meine Verkäufe',
    restaurant: 'Restaurant',
    supplier: 'Lieferant',
    restaurantOwner: 'Restaurantbesitzer',
    taxIdVat: 'Steuernummer / USt-IdNr.',
    city: 'Stadt',
    cuisineType: 'Küche / Typ',
    categories: 'Kategorien',
    businessLocations: 'Geschäftsstandorte',
    bankDetails: 'Bankdaten',
    add: 'Hinzufügen',
    addAddress: 'Adresse hinzufügen',
    addTaxId: 'Steuernummer hinzufügen',
    addBankDetails: 'Bankdaten hinzufügen',
    notSet: 'Nicht festgelegt',
    saveChanges: 'Änderungen speichern',
    selected: 'ausgewählt',
    locationsHelp: 'Tippen Sie auf jeden Standort, den Sie in Ihrem Profil anzeigen möchten',
    manageAddresses: 'Adressen verwalten',
    cityLocation: 'Stadt / Standort',
    useGps: 'GPS verwenden',
    useMyLocation: 'Meinen Standort verwenden',
    detecting: 'Suche…',
    halal: 'Halal',
    aboutOptional: 'Eine kurze Beschreibung Ihres Restaurants...',
    yourName: 'Ihr Name',
    restaurantName: 'Restaurantname',
    businessName: 'Firmenname',
    description: 'Beschreibung',
    bio: 'Über',
    website: 'Webseite (optional)',
    requiredField: '* Pflichtfeld',

    // AI
    aiInsights: 'KI-Einblicke',
    poweredByGemini: 'Powered by Gemini',
    refreshInsights: 'Einblicke aktualisieren',
    tryAgain: 'Erneut versuchen',
    generateInsights: 'Einblicke generieren',
    analyseYourSales: 'Verkaufsdaten analysieren',
    aiHelpText: 'KI-gestützte Einblicke in Umsatz, Top-Produkte und Wachstumschancen.',

    // Common
    save: 'Speichern',
    cancel: 'Abbrechen',
    close: 'Schließen',
    back: 'Zurück',
    loading: 'Laden…',
    submit: 'Absenden',
    confirm: 'Bestätigen',
    delete: 'Löschen',
    edit: 'Bearbeiten',
    search: 'Suchen',
    filter: 'Filter',
    addToCart: 'In den Warenkorb',
    order: 'Bestellung',
    orders: 'Bestellungen',
    products: 'Produkte',
    analytics: 'Analysen',
    settings: 'Einstellungen',
    language: 'Sprache',
    halalCertified: 'Halal-zertifiziert',
    rating: 'Bewertung',
    location: 'Standort',
    phone: 'Telefon',
    email: 'E-Mail',
    address: 'Adresse',

    // Landing page extra
    browseByCategory: 'Nach Kategorie stöbern',
    howItWorks: 'So funktioniert es',
    howItWorksStep1Title: 'Konto erstellen',
    howItWorksStep1Desc: 'Registrieren Sie sich in wenigen Minuten als Restaurantbesitzer oder Lieferant. Keine versteckten Gebühren.',
    howItWorksStep2Title: 'Stöbern & Bestellen',
    howItWorksStep2Desc: 'Stöbern Sie bei verifizierten Halal-Lieferanten und bestellen Sie mit einem Klick.',
    howItWorksStep3Title: 'Lieferung verfolgen',
    howItWorksStep3Desc: 'Verfolgen Sie Ihre Lieferung in Echtzeit und verwalten Sie alle Bestellungen an einem Ort.',
    gdprCompliant: 'DSGVO-konform',
    halalVerifiedBadge: 'Halal-zertifizierte Lieferanten',
    noHiddenFees: 'Keine versteckten Gebühren',
    noProductsFound: 'Keine Produkte gefunden. Werden Sie der erste Lieferant!',
    noSuppliersYet: 'Noch keine verifizierten Lieferanten.',
    outOfStock: 'Nicht verfügbar',
    statsRestaurants: 'Restaurants',
    statsVerifiedSuppliers: 'Geprüfte Lieferanten',
    statsOrdersPlaced: 'Bestellungen',
    statsAverageRating: 'Durchschnittsbewertung',
    catAll: 'Alle',
    catMeat: 'Fleisch',
    catPoultry: 'Geflügel',
    catSeafood: 'Meeresfrüchte',
    catDairy: 'Milchprodukte',
    catVegetables: 'Gemüse',
    catFruits: 'Obst',
    catBakery: 'Backwaren',
    catBeverages: 'Getränke',
    catSpices: 'Gewürze',
    catOther: 'Sonstiges',

    // About page
    aboutTitle: 'Über ProCuro',
    aboutIntro: 'ProCuro ist eine B2B-Halal-Beschaffungsplattform, die zertifizierte Halal-Lieferanten mit Restaurantbesitzern in ganz Deutschland verbindet. Unsere Mission ist es, Halal-Lieferketten transparent, effizient und vertrauenswürdig zu machen.',
    aboutCard1Title: 'Geprüftes Halal',
    aboutCard1Desc: 'Jeder Lieferant auf ProCuro hält eine gültige Halal-Zertifizierung, die von unserem Admin-Team geprüft wurde.',
    aboutCard2Title: 'Gemeinschaft zuerst',
    aboutCard2Desc: 'Entwickelt für die Halal-Geschäftsgemeinschaft in Deutschland — Lieferanten, Restaurantbesitzer und Caterer.',
    aboutCard3Title: 'Made in Germany',
    aboutCard3Desc: 'Hauptsitz in Paderborn, NRW. Vollständig konform mit deutschen und EU-Vorschriften.',
    aboutOurStory: 'Unsere Geschichte',
    aboutStoryP1: 'ProCuro wurde gegründet, um ein echtes Problem zu lösen: Restaurantbesitzer in Deutschland hatten Schwierigkeiten, zuverlässige, zertifizierte Halal-Lieferanten zu finden — und Lieferanten hatten keinen einfachen Weg, ihre Kunden zu erreichen. Wir haben eine Plattform entwickelt, die diese Lücke mit einem nahtlosen Bestellsystem, Echtzeit-Kommunikation und transparenter Zertifizierungsverifizierung überbrückt.',
    aboutStoryP2: 'Heute bedient ProCuro Dutzende von verifizierten Lieferanten und Hunderte von Restaurants in ganz Deutschland, mit Fokus auf Qualität, Vertrauen und Gemeinschaft.',
    contactUs: 'Kontakt',
    aboutLocation: 'Standort: Paderborn, Nordrhein-Westfalen, Deutschland',

    // Careers page
    careersTitle: 'Karriere bei ProCuro',
    careersSubtitle: 'Gestalten Sie mit uns die Zukunft der Halal-Beschaffung in Deutschland.',
    careersWhyTitle: 'Warum ProCuro?',
    careersWhyDesc: 'Wir sind ein mission-orientiertes Startup mit Sitz in Paderborn, NRW, das ein echtes Problem für die Halal-Geschäftsgemeinschaft löst. Wir bieten ein kollaboratives Umfeld, wettbewerbsfähige Gehälter, flexible Arbeitszeiten und die Möglichkeit, einen bedeutenden Beitrag zu leisten.',
    careersOpenPositions: 'Offene Stellen',
    careersApplyEmail: 'Per E-Mail bewerben',
    careersNoRole: 'Keine passende Stelle dabei? Wir freuen uns trotzdem über Ihre Bewerbung.',
    careersSpontaneous: 'Initiativbewerbung senden →',
    careersJob1Title: 'Full-Stack-Entwickler (React / Node.js)',
    careersJob1Type: 'Vollzeit',
    careersJob1Location: 'Paderborn, NRW (Remote möglich)',
    careersJob1Desc: 'Helfen Sie beim Aufbau und der Skalierung unserer Beschaffungsplattform. Erfahrung mit React, Supabase und TypeScript bevorzugt.',
    careersJob2Title: 'Business Development Manager',
    careersJob2Type: 'Vollzeit',
    careersJob2Location: 'Paderborn, NRW',
    careersJob2Desc: 'Fördern Sie Partnerschaften mit Halal-Lieferanten und Restaurantketten in ganz Deutschland. Deutsch und Englisch erforderlich.',
    careersJob3Title: 'Customer Success Specialist',
    careersJob3Type: 'Teilzeit / Vollzeit',
    careersJob3Location: 'Remote (Deutschland)',
    careersJob3Desc: 'Unterstützen Sie unsere wachsende Lieferanten- und Restaurantbesitzer-Community. Fließendes Deutsch erforderlich.',

    // Press page
    pressTitle: 'Presse & Medien',
    pressSubtitle: 'Informationen und Ressourcen für Journalisten und Medienschaffende.',
    pressAboutTitle: 'Über ProCuro',
    pressAboutDesc: 'ProCuro ist Deutschlands führende B2B-Halal-Beschaffungsplattform, die zertifizierte Halal-Lieferanten mit Restaurantbesitzern und Caterern verbindet. Gegründet in Paderborn, NRW, bringt ProCuro Transparenz, Vertrauen und Effizienz in Halal-Lieferketten in ganz Deutschland.',
    pressKeyFacts: 'Fakten',
    pressFoundedLabel: 'Gegründet',
    pressHQLabel: 'Hauptsitz',
    pressMarketLabel: 'Markt',
    pressPlatformLabel: 'Plattform',
    pressLanguagesLabel: 'Sprachen',
    pressMarketValue: 'B2B Halal Lebensmittelbeschaffung, Deutschland',
    pressPlatformValue: 'Web-basiertes SaaS (React / Supabase)',
    pressLanguagesValue: 'Deutsch, Englisch, Arabisch (geplant)',
    pressContactTitle: 'Pressekontakt',
    pressContactDesc: 'Für Presseanfragen, Interviewanfragen oder Medienmaterial wenden Sie sich bitte an unser Team.',
    pressContactButton: 'Presseteam kontaktieren',
    pressBrandAssetsTitle: 'Marken-Assets',
    pressBrandAssetsDesc: 'Logo-Dateien, Markenrichtlinien und hochauflösende Bilder auf Anfrage erhältlich. Schreiben Sie uns an support@procuro.com.',
    pressStatRestaurants: 'Restaurants',
    pressStatSuppliers: 'Lieferanten',
    pressStatRating: 'Plattformbewertung',

    // Help Center page
    helpTitle: 'Hilfezentrum',
    helpSubtitle: 'Haben Sie eine Frage oder ein Problem? Füllen Sie das Formular aus und wir melden uns innerhalb von 24 Stunden.',
    helpNameLabel: 'Name *',
    helpNamePlaceholder: 'Ihr Name',
    helpEmailPlaceholder: 'sie@beispiel.de',
    helpTopicLabel: 'Thema',
    helpTopicPlaceholder: 'Thema wählen...',
    helpMessageLabel: 'Nachricht *',
    helpMessagePlaceholder: 'Beschreiben Sie Ihr Anliegen ausführlich...',
    helpSendMessage: 'Nachricht senden',
    helpEmailDirect: 'Oder schreiben Sie uns direkt an',
    helpSentTitle: 'Nachricht gesendet!',
    helpSentDesc: 'Ihr E-Mail-Programm sollte sich geöffnet haben. Falls nicht, schreiben Sie uns direkt an',
    helpRequiredError: 'Bitte füllen Sie alle Pflichtfelder aus',
    helpTopicAccount: 'Konto & Registrierung',
    helpTopicOrders: 'Bestellungen & Lieferung',
    helpTopicPayments: 'Zahlungen & Rechnungen',
    helpTopicHalal: 'Halal-Zertifizierung',
    helpTopicTechnical: 'Technisches Problem',
    helpTopicOther: 'Sonstiges',

    // Legal pages
    privacyTitle: 'Datenschutzerklärung',
    privacySubtitle: 'Zuletzt aktualisiert: Mai 2025',
    privacyLegalNote: '',
    termsTitle: 'Allgemeine Geschäftsbedingungen',
    termsSubtitle: 'Stand: Mai 2025',
    termsLegalNote: '',
  },
}

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    try { return localStorage.getItem('procuro_lang') || 'en' } catch { return 'en' }
  })

  function setLanguage(l) {
    if (!LANGS.includes(l)) return
    setLang(l)
    try { localStorage.setItem('procuro_lang', l) } catch {}
    try { document.documentElement.lang = l } catch {}
  }

  function t(key) {
    return T[lang]?.[key] ?? T.en?.[key] ?? key
  }

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  return useContext(LanguageContext)
}
